version: "3"

includes:
  common: ./build/Taskfile.yml
  windows: ./build/windows/Taskfile.yml
  darwin: ./build/darwin/Taskfile.yml
  linux: ./build/linux/Taskfile.yml

vars:
  APP_NAME: "zettl"
  BIN_DIR: "bin"
  VITE_PORT: "{{.WAILS_VITE_PORT | default 9245}}"
  TAGS: sqlite_fts5
  APP_CERTIFICATE: "3rd Party Mac Developer Application: Victor Lin (44UKKXL94E)"
  PKG_CERTIFICATE: "3rd Party Mac Developer Installer: Victor Lin (44UKKXL94E)"

tasks:
  build:
    summary: Build app
    cmds:
      - task: "{{OS}}:build"
  package:
    summary: Package app
    cmds:
      - task: "{{OS}}:package"
  run:
    summary: Run app
    cmds:
      - task: "{{OS}}:run"
  dev:
    summary: Dev mode
    cmds:
      - ZETTL_ENV=development wails3 dev -config ./build/config.yml -port {{.VITE_PORT}}
