#[derive(PartialEq, Eq, Hash, Copy, Clone, Debug)]
pub enum ContentType {
    Ai,
    Apk,
    ApplePlist,
    Asm,
    Asp,
    Batch,
    Bmp,
    Bzip,
    C,
    Cab,
    Cat,
    Chm,
    Coff,
    Crx,
    Cs,
    Css,
    Csv,
    Deb,
    Dex,
    Dmg,
    Doc,
    Docx,
    Elf,
    Emf,
    Eml,
    Epub,
    Flac,
    Gif,
    Go,
    Gzip,
    Hlp,
    Html,
    Ico,
    Ini,
    InternetShortcut,
    Iso,
    Jar,
    Java,
    JavaBytecode,
    JavaScript,
    Jpeg,
    Json,
    Latex,
    Lisp,
    Lnk,
    M3u,
    Macho,
    Makefile,
    Markdown,
    Mht,
    Mp3,
    Mp4,
    MsCompress,
    Msi,
    Mum,
    Odex,
    Odp,
    Ods,
    Odt,
    Ogg,
    Outlook,
    Pcap,
    Pdf,
    PeBin,
    Pem,
    Perl,
    Php,
    Png,
    PostScript,
    PowerShell,
    Ppt,
    Pptx,
    Python,
    PythonBytecode,
    Rar,
    Rdf,
    Rpm,
    Rst,
    Rtf,
    Ruby,
    Rust,
    Scala,
    SevenZip,
    Shell,
    Smali,
    Sql,
    Squashfs,
    Svg,
    Swf,
    SymlinkText,
    Tar,
    Tga,
    Tiff,
    Torrent,
    Ttf,
    Txt,
    Unknown,
    Vba,
    Wav,
    Webm,
    Webp,
    WinRegistry,
    Wmf,
    Xar,
    Xls,
    Xlsb,
    Xlsx,
    Xml,
    Xpi,
    Xz,
    Yaml,
    Zip,
    ZlibStream,
}

pub const CONTENT_TYPES: [ContentType; 113] = [
    ContentType::Ai,
    ContentType::Apk,
    ContentType::ApplePlist,
    ContentType::Asm,
    ContentType::Asp,
    ContentType::Batch,
    ContentType::Bmp,
    ContentType::Bzip,
    ContentType::C,
    ContentType::Cab,
    ContentType::Cat,
    ContentType::Chm,
    ContentType::Coff,
    ContentType::Crx,
    ContentType::Cs,
    ContentType::Css,
    ContentType::Csv,
    ContentType::Deb,
    ContentType::Dex,
    ContentType::Dmg,
    ContentType::Doc,
    ContentType::Docx,
    ContentType::Elf,
    ContentType::Emf,
    ContentType::Eml,
    ContentType::Epub,
    ContentType::Flac,
    ContentType::Gif,
    ContentType::Go,
    ContentType::Gzip,
    ContentType::Hlp,
    ContentType::Html,
    ContentType::Ico,
    ContentType::Ini,
    ContentType::InternetShortcut,
    ContentType::Iso,
    ContentType::Jar,
    ContentType::Java,
    ContentType::JavaBytecode,
    ContentType::JavaScript,
    ContentType::Jpeg,
    ContentType::Json,
    ContentType::Latex,
    ContentType::Lisp,
    ContentType::Lnk,
    ContentType::M3u,
    ContentType::Macho,
    ContentType::Makefile,
    ContentType::Markdown,
    ContentType::Mht,
    ContentType::Mp3,
    ContentType::Mp4,
    ContentType::MsCompress,
    ContentType::Msi,
    ContentType::Mum,
    ContentType::Odex,
    ContentType::Odp,
    ContentType::Ods,
    ContentType::Odt,
    ContentType::Ogg,
    ContentType::Outlook,
    ContentType::Pcap,
    ContentType::Pdf,
    ContentType::PeBin,
    ContentType::Pem,
    ContentType::Perl,
    ContentType::Php,
    ContentType::Png,
    ContentType::PostScript,
    ContentType::PowerShell,
    ContentType::Ppt,
    ContentType::Pptx,
    ContentType::Python,
    ContentType::PythonBytecode,
    ContentType::Rar,
    ContentType::Rdf,
    ContentType::Rpm,
    ContentType::Rst,
    ContentType::Rtf,
    ContentType::Ruby,
    ContentType::Rust,
    ContentType::Scala,
    ContentType::SevenZip,
    ContentType::Shell,
    ContentType::Smali,
    ContentType::Sql,
    ContentType::Squashfs,
    ContentType::Svg,
    ContentType::Swf,
    ContentType::SymlinkText,
    ContentType::Tar,
    ContentType::Tga,
    ContentType::Tiff,
    ContentType::Torrent,
    ContentType::Ttf,
    ContentType::Txt,
    ContentType::Unknown,
    ContentType::Vba,
    ContentType::Wav,
    ContentType::Webm,
    ContentType::Webp,
    ContentType::WinRegistry,
    ContentType::Wmf,
    ContentType::Xar,
    ContentType::Xls,
    ContentType::Xlsb,
    ContentType::Xlsx,
    ContentType::Xml,
    ContentType::Xpi,
    ContentType::Xz,
    ContentType::Yaml,
    ContentType::Zip,
    ContentType::ZlibStream,
];

impl ContentType {
    pub fn is_text(&self) -> bool {
        match self {
            ContentType::Ai => false,
            ContentType::Apk => false,
            ContentType::ApplePlist => true,
            ContentType::Asm => true,
            ContentType::Asp => true,
            ContentType::Batch => true,
            ContentType::Bmp => false,
            ContentType::Bzip => false,
            ContentType::C => true,
            ContentType::Cab => false,
            ContentType::Cat => false,
            ContentType::Chm => false,
            ContentType::Coff => false,
            ContentType::Crx => false,
            ContentType::Cs => true,
            ContentType::Css => true,
            ContentType::Csv => true,
            ContentType::Deb => false,
            ContentType::Dex => false,
            ContentType::Dmg => false,
            ContentType::Doc => false,
            ContentType::Docx => false,
            ContentType::Elf => false,
            ContentType::Emf => false,
            ContentType::Eml => true,
            ContentType::Epub => false,
            ContentType::Flac => false,
            ContentType::Gif => false,
            ContentType::Go => true,
            ContentType::Gzip => false,
            ContentType::Hlp => false,
            ContentType::Html => true,
            ContentType::Ico => false,
            ContentType::Ini => true,
            ContentType::InternetShortcut => true,
            ContentType::Iso => false,
            ContentType::Jar => false,
            ContentType::Java => true,
            ContentType::JavaBytecode => false,
            ContentType::JavaScript => true,
            ContentType::Jpeg => false,
            ContentType::Json => true,
            ContentType::Latex => true,
            ContentType::Lisp => true,
            ContentType::Lnk => false,
            ContentType::M3u => false,
            ContentType::Macho => false,
            ContentType::Makefile => true,
            ContentType::Markdown => true,
            ContentType::Mht => true,
            ContentType::Mp3 => false,
            ContentType::Mp4 => false,
            ContentType::MsCompress => false,
            ContentType::Msi => false,
            ContentType::Mum => true,
            ContentType::Odex => false,
            ContentType::Odp => false,
            ContentType::Ods => false,
            ContentType::Odt => false,
            ContentType::Ogg => false,
            ContentType::Outlook => false,
            ContentType::Pcap => false,
            ContentType::Pdf => false,
            ContentType::PeBin => false,
            ContentType::Pem => true,
            ContentType::Perl => true,
            ContentType::Php => true,
            ContentType::Png => false,
            ContentType::PostScript => false,
            ContentType::PowerShell => true,
            ContentType::Ppt => false,
            ContentType::Pptx => false,
            ContentType::Python => true,
            ContentType::PythonBytecode => false,
            ContentType::Rar => false,
            ContentType::Rdf => true,
            ContentType::Rpm => false,
            ContentType::Rst => true,
            ContentType::Rtf => true,
            ContentType::Ruby => true,
            ContentType::Rust => true,
            ContentType::Scala => true,
            ContentType::SevenZip => false,
            ContentType::Shell => true,
            ContentType::Smali => true,
            ContentType::Sql => true,
            ContentType::Squashfs => false,
            ContentType::Svg => true,
            ContentType::Swf => false,
            ContentType::SymlinkText => true,
            ContentType::Tar => false,
            ContentType::Tga => false,
            ContentType::Tiff => false,
            ContentType::Torrent => false,
            ContentType::Ttf => false,
            ContentType::Txt => true,
            ContentType::Unknown => false,
            ContentType::Vba => true,
            ContentType::Wav => false,
            ContentType::Webm => false,
            ContentType::Webp => false,
            ContentType::WinRegistry => true,
            ContentType::Wmf => false,
            ContentType::Xar => false,
            ContentType::Xls => false,
            ContentType::Xlsb => false,
            ContentType::Xlsx => false,
            ContentType::Xml => true,
            ContentType::Xpi => false,
            ContentType::Xz => false,
            ContentType::Yaml => true,
            ContentType::Zip => false,
            ContentType::ZlibStream => false,
        }
    }

    pub fn key(&self) -> &str {
        match self {
            ContentType::Ai => "Ai",
            ContentType::Apk => "Apk",
            ContentType::ApplePlist => "ApplePlist",
            ContentType::Asm => "Asm",
            ContentType::Asp => "Asp",
            ContentType::Batch => "Batch",
            ContentType::Bmp => "Bmp",
            ContentType::Bzip => "Bzip",
            ContentType::C => "C",
            ContentType::Cab => "Cab",
            ContentType::Cat => "Cat",
            ContentType::Chm => "Chm",
            ContentType::Coff => "Coff",
            ContentType::Crx => "Crx",
            ContentType::Cs => "Cs",
            ContentType::Css => "Css",
            ContentType::Csv => "Csv",
            ContentType::Deb => "Deb",
            ContentType::Dex => "Dex",
            ContentType::Dmg => "Dmg",
            ContentType::Doc => "Doc",
            ContentType::Docx => "Docx",
            ContentType::Elf => "Elf",
            ContentType::Emf => "Emf",
            ContentType::Eml => "Eml",
            ContentType::Epub => "Epub",
            ContentType::Flac => "Flac",
            ContentType::Gif => "Gif",
            ContentType::Go => "Go",
            ContentType::Gzip => "Gzip",
            ContentType::Hlp => "Hlp",
            ContentType::Html => "Html",
            ContentType::Ico => "Ico",
            ContentType::Ini => "Ini",
            ContentType::InternetShortcut => "InternetShortcut",
            ContentType::Iso => "Iso",
            ContentType::Jar => "Jar",
            ContentType::Java => "Java",
            ContentType::JavaBytecode => "JavaBytecode",
            ContentType::JavaScript => "JavaScript",
            ContentType::Jpeg => "Jpeg",
            ContentType::Json => "Json",
            ContentType::Latex => "Latex",
            ContentType::Lisp => "Lisp",
            ContentType::Lnk => "Lnk",
            ContentType::M3u => "M3u",
            ContentType::Macho => "Macho",
            ContentType::Makefile => "Makefile",
            ContentType::Markdown => "Markdown",
            ContentType::Mht => "Mht",
            ContentType::Mp3 => "Mp3",
            ContentType::Mp4 => "Mp4",
            ContentType::MsCompress => "MsCompress",
            ContentType::Msi => "Msi",
            ContentType::Mum => "Mum",
            ContentType::Odex => "Odex",
            ContentType::Odp => "Odp",
            ContentType::Ods => "Ods",
            ContentType::Odt => "Odt",
            ContentType::Ogg => "Ogg",
            ContentType::Outlook => "Outlook",
            ContentType::Pcap => "Pcap",
            ContentType::Pdf => "Pdf",
            ContentType::PeBin => "PeBin",
            ContentType::Pem => "Pem",
            ContentType::Perl => "Perl",
            ContentType::Php => "Php",
            ContentType::Png => "Png",
            ContentType::PostScript => "PostScript",
            ContentType::PowerShell => "PowerShell",
            ContentType::Ppt => "Ppt",
            ContentType::Pptx => "Pptx",
            ContentType::Python => "Python",
            ContentType::PythonBytecode => "PythonBytecode",
            ContentType::Rar => "Rar",
            ContentType::Rdf => "Rdf",
            ContentType::Rpm => "Rpm",
            ContentType::Rst => "Rst",
            ContentType::Rtf => "Rtf",
            ContentType::Ruby => "Ruby",
            ContentType::Rust => "Rust",
            ContentType::Scala => "Scala",
            ContentType::SevenZip => "SevenZip",
            ContentType::Shell => "Shell",
            ContentType::Smali => "Smali",
            ContentType::Sql => "Sql",
            ContentType::Squashfs => "Squashfs",
            ContentType::Svg => "Svg",
            ContentType::Swf => "Swf",
            ContentType::SymlinkText => "SymlinkText",
            ContentType::Tar => "Tar",
            ContentType::Tga => "Tga",
            ContentType::Tiff => "Tiff",
            ContentType::Torrent => "Torrent",
            ContentType::Ttf => "Ttf",
            ContentType::Txt => "Txt",
            ContentType::Unknown => "Unknown",
            ContentType::Vba => "Vba",
            ContentType::Wav => "Wav",
            ContentType::Webm => "Webm",
            ContentType::Webp => "Webp",
            ContentType::WinRegistry => "WinRegistry",
            ContentType::Wmf => "Wmf",
            ContentType::Xar => "Xar",
            ContentType::Xls => "Xls",
            ContentType::Xlsb => "Xlsb",
            ContentType::Xlsx => "Xlsx",
            ContentType::Xml => "Xml",
            ContentType::Xpi => "Xpi",
            ContentType::Xz => "Xz",
            ContentType::Yaml => "Yaml",
            ContentType::Zip => "Zip",
            ContentType::ZlibStream => "ZlibStream",
        }
    }
}
